services:
  catalogue:
    build: ./catalogue
    container_name: catalogue
    ports:
      - "8000:8000"
    volumes:
      - ./catalogue/data:/app/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"

  raspi-01:
    build: ./raspberrypi
    container_name: raspi-01
    env_file:
      - .env
    environment:
      DEVICE_ID: raspi-01
      DEVICE_NAME: Plant Sensor Node 1
    depends_on:
      - catalogue
      - mosquitto

  raspi-02:
    build: ./raspberrypi
    container_name: raspi-02
    env_file:
      - .env
    environment:
      DEVICE_ID: raspi-02
      DEVICE_NAME: Plant Sensor Node 2
    depends_on:
      - catalogue
      - mosquitto

  raspi-03:
    build: ./raspberrypi
    container_name: raspi-03
    env_file:
      - .env
    environment:
      DEVICE_ID: raspi-03
      DEVICE_NAME: Plant Sensor Node 3
    depends_on:
      - catalogue
      - mosquitto

  raspi-04:
    build: ./raspberrypi
    container_name: raspi-04
    env_file:
      - .env
    environment:
      DEVICE_ID: raspi-04
      DEVICE_NAME: Plant Sensor Node 4
    depends_on:
      - catalogue
      - mosquitto